<?
$customer_name		= "客户名";
$city			= "城市";
$state			= "省份";
$address		= "地址";
$zipcode		= "邮政编码";
$website		= "网址";
$category		= "类别";
$create_time		= "建立时间";
$create_by		= "添加人";
$back			= "返回管理界面";
$phone			= "电话";

$category = "类别";
$contact = "联系人";
$note = "备注";
$create_time = "创建时间";
$create_by = "创建人";
$address = "地址";
$website = "网址";
$priority = "重要度";
$add_record = "添加记录";
$edit_record = "修改记录";
$record_deleted = "记录已删除";
$customer_detail = "客户信息";
$note_detail = "备注信息";
$contact_detail = "联系人信息";
$contact_update_error	= "联系人信息无法更新";
$customer_add_error	= "无法添加客户";
$note_add_error		=	"无法添加备注信息";
$note_add_success	=	"成功添加备注信息";
$no_dial_list		=	"拨号列表为空";
$records_in_dial_list_table		=	"等待拨打的电话数目: ";
$start_campaign					=	"启动拨号系统";
$get_a_phone_number				=	"获取一个电话号码";
?>
