<?
//En for mangaer
$add_note = "A note has been added ";
$add_account = "New account record added";
$update_rec = "A record has been updated";
$rec_cannot_update = "The record could not be updated";
$delete_rec = "Record Deleted";
$rec_cannot_delete = "The record could not be deleted";
$username = "User Name ";
$password = "Password ";
$extension = "Extension ";
$extensions = "Extensions, use comma between extensions ";
$continue = "Continue";
$obligatory_fields = "* Obligatory fields";
$adding_account = "Adding Account";
$extension_manager = "Extension Manager";
$system_monitor = "System Monitor";
$back = "Back";
$usertype = "User Type";
$usertype_note = "support admin only";
$active_channels = "Active Channels";
$predictive_dialer = "Predictive Dialer";
$msgChannelsInfo = "reading message,please stand by...";
?>
