<?
//Cn for mangaer
$add_note = "一条记录被添加 ";
$add_account = "添加了一个新帐号";
$update_rec = "该记录已更新";
$rec_cannot_update = "该记录不能被更新";
$delete_rec = "记录被删除";
$rec_cannot_delete = "该记录不能被删除";
$username = "用户名 ";
$password = "密码 ";
$extension = "分机号码 ";
$extensions = "可观察的分机, 分机之间用逗号隔开 ";
$continue = "继续";
$obligatory_fields = "带*的为必填项目";
$adding_account = "添加用户";
$extension_manager = "分机用户管理";
$system_monitor = "系统分机状态";
$back = "返回";
$usertype = "用户类型";
$usertype_note = "目前只支持admin";
?>
