<?
$welcome="欢迎 ";
$extension="你的分机是 ";
$waiting="请等待 ";
$listening="正在监听 ";
$processing_please_wait = "正在处理, 请稍候";
$logout="登出 ";
$transfer="转接";
$stand_by="请稍候";
$incoming="你有新的来电";
$dial_out="正在拨号";
$customer_name = '客户名';
$category = '类别';
$contact = "联系人";
$note = "备注";
$create_time = "创建时间";
$create_by = "创建人";
$address = "地址";
$website = "网址";
$priority = "重要度";
$add_record = "添加记录";
$edit_record = "修改记录";
$record_deleted = "记录已删除";
$customer_detail = "客户信息";
$note_detail = "备注信息";
$contact_detail = "联系人信息";
$contact_update_error	= "联系人信息无法更新";
$customer_add_error	= "无法添加客户";
$note_add_error		=	"无法添加备注信息";
$note_add_success	=	"成功添加备注信息";

?>