#!/bin/sh   
#   singhead monitor for astercc daemons
#     
# |||||||||||||||||||| CONFIGURATION SECTION  ||||||||||||||||||||
# --------------------                              --------------------   
#
# the absolute path to your asterccd shell, must included shell name, can not include options
asterccdpath="/opt/asterisk/scripts/astercc/asterccd"
# the absolute path to your monitor log, can not include logfile name
monitorlogpath="/opt/asterisk/scripts/astercc/"
i=0
#
# --------------------                              --------------------
# ||||||||||||||||||||   END CONFIGURATION SECTION  ||||||||||||||||||||

if [ ! -f $monitorlogpath/asterccmonitor.log ];then 
	echo 0 > $monitorlogpath/asterccmonitor.log
else
	sed -i '1d' $monitorlogpath/asterccmonitor.log
	sed -i '1i\0' $monitorlogpath/asterccmonitor.log
fi

while   [   1   ]   
	do
		sleep  60
		asterccpid=`ps -ef |grep -v grep |grep -E /asterc[.\ ]+-d |awk '{print $2}'`
		asterrcpid=`ps -ef |grep -v grep |grep -E /asterr[.\ ]+-d |awk '{print $2}'`
		asterlcpid=`ps -ef |grep -v grep |grep -E /asterccloc[.\ ]+-d |awk '{print $2}'`
		if [ "x$asterccpid" == "x" -o "x$asterrcpid" == "x" -o "x$asterlcpid" == "x" ]
		then
			if test -s $asterccdpath; then
				$asterccdpath > /dev/null
				if [ $? -ne 0 ];then				  
				  echo "start asterccd faild at "`date`" ERROR="$? >> $monitorlogpath/asterccmonitor.log
				  break_tip=`grep "^break_tip.*=" astercc.conf |awk -F = '{print $2}' |sed -e 's/[ ]*[ ]//g'`
				  tip_times=`grep "^tip_times.*=" astercc.conf |awk -F = '{print $2}' |sed -e 's/[ ]*[ ]//g'`
				  tip_limit=`sed -n -e"1p" $monitorlogpath/asterccmonitor.log`
				  if [ $break_tip -ne 0 -a $tip_limit -lt $tip_times ];then
				    let tip_limit=tip_limit+1
				    sed -i '1d' $monitorlogpath/asterccmonitor.log
				    sed -i '1i'${tip_limit} $monitorlogpath/asterccmonitor.log
				    host=`grep "^server.*=" astercc.conf |awk -F = '{print $2}' |sed -e 's/[ ]*[ ]//g'`     #for asterisk host IP and port
				    port=`grep "^port.*=" astercc.conf |awk -F = '{print $2}' |sed -e 's/[ ]*[ ]//g'`
				    ami_admin=`grep "^admin_amiuser.*=" astercc.conf |awk -F = '{print $2}' |sed -e 's/[ ]*[ ]//g'`
				    ami_secret=`grep "^admin_amisecret.*=" astercc.conf |awk -F = '{print $2}' |sed -e 's/[ ]*[ ]//g'`
				    admin_context=`grep "^admin_context.*=" astercc.conf |awk -F = '{print $2}' |sed -e 's/[ ]*[ ]//g'`
				    admin_phone=`grep "^admin_phone.*=" astercc.conf |awk -F = '{print $2}' |sed -e 's/[ ]*[ ]//g'`
				    (echo Action: login
				    sleep 1
				    echo Username: $ami_admin               
				    sleep 1
				    echo Secret: $ami_secret                
				    sleep 1
				    echo Events: off
				    sleep 1
				    echo ""
				    sleep 1
				    echo Action: Originate
				    sleep 1
				    echo Channel: LOCAL/$admin_phone@$admin_context 
				    sleep 1
				    echo Application: SayUnixTime
				    sleep 1
				    echo Timeout: 30000
				    sleep 1
				    echo Priority: 1
				    sleep 1
				    echo "")|telnet $host $port > /dev/null
				  fi 
				else
					echo "start asterccd start successed at "`date` >> $monitorlogpath/asterccmonitor.log
				fi
			else
				echo Not asterccd in $asterccdpath >> $monitorlogpath/asterccmonitor.log
			fi	
		fi
done
